spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MiniposterPostsDatabase
    username: miniposter
    password: miniposter_password
    driverClassName: org.postgresql.Driver
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    queue:
      postQueue: addPostQueue
      analyticsQueue: addAnalyticsRecordQueue
    exchange:
      postExchange: miniposter.post
      analyticsExchange: miniposter.analytics

server:
  port: 8002
