server:
  port: 8000

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    queue:
      postQueue: addPostQueue
    exchange:
      postExchange: miniposter.post

auth-server:
  url: ${AUTH_SERVER_URI}
