server:
  port: 8000

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    queue:
      postQueue: addPostQueue
    exchange:
      postExchange: miniposter.post

auth-server:
  url: ${AUTH_SERVER_URI}
redirect:
    auth-server-url: ${AUTH_SERVER_URI}
    analytics-service-url: ${ANALYTICS_SERVICE_URL}
    post-service-url: ${POST_SERVICE_URL}
    filter-service-url: ${FILTER_SERVICE_URL}