spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: postgres
    password: adnub
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    ddl-auto: create-drop
  security:
    user:
      name: user
      password: password

server:
  port: 8000

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
