spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_URI}/${DATABASE_NAME}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password

server:
  port: 8004
